module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Users', [
    {
      id: '6bbf0744-74b4-46b9-bb05-53905d4538e7',
      firstName: 'karthick',
      lastName: 'k',
      Email: 'kkrishnagowda@primesoft.net',
      temproaryPassword: null,
      temproaryPasswordExpiry: null,
      roleId: 1,
      accountType: 'I',
      status: 'enabled',
      permanentPassword: '123456',
      otpHash: null,
      otpExpiry: null,
      otpAttempts: null,
      otpWrongAttempts: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '6bbf0744-74b4-46b9-bb05-53905d4538e98',
      firstName: 'karthick',
      lastName: 'k',
      Email: 'kkrishnagowda@primesoft.net',
      temproaryPassword: null,
      temproaryPasswordExpiry: null,
      roleId: 2,
      accountType: 'I',
      status: 'enabled',
      permanentPassword: '123456',
      otpHash: null,
      otpExpiry: null,
      otpAttempts: null,
      otpWrongAttempts: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ], {}),
  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Users', null, {}),
};
